folderPaths = { 'Z:\HarveyLab\Ari\2P Data\ResScan\AM131\140805',...
                'Z:\HarveyLab\Ari\2P Data\ResScan\AM127\140804',...
                'Z:\HarveyLab\Ari\2P Data\ResScan\AM127\140805',...
                'Z:\HarveyLab\Ari\2P Data\ResScan\AM136\140806',...
                'Z:\HarveyLab\Ari\2P Data\ResScan\AM131\140806',...
                'Z:\HarveyLab\Ari\2P Data\ResScan\AM135\140806',...
                'Z:\HarveyLab\Ari\2P Data\ResScan\AM127\140806'};
            
% fileStrings = { 'AM\d\d\d.*\d\d\d_\d\d\d.tif',...
%                 'AM\d\d\d.*\d\d\d_\d\d\d.tif',...
%                 'AM\d\d\d.*\d\d\d_\d\d\d.tif',...
%                 'AM\d\d\d.*\d\d\d_\d\d\d.tif',...
%                 'AM\d\d\d.*\d\d\d_\d\d\d.tif',...
%                 'AM\d\d\d.*\d\d\d_\d\d\d.tif',...
%                 'AM\d\d\d.*\d\d\d_\d\d\d.tif'};
fileStrings = repmat({'AM\d\d\d.*\d\d\d_\d\d\d.tif'},length(folderPaths),1);
            

batchLocalAffine(folderPaths,fileStrings);