function plotDFFTraces(dFFTraces,frameRate,cellIDs,maxRows,plotFrames)
%plotDFFTraces.m Plots dF/F traces and can plot image of all cells with
%cell number and filters overlaid
%
%INPUTS
%dFFTraces - nCells x nFrames array of dF/F traces generated by
%   getDFFTraces.m
%frameRate - frame rate of acquisition for calculating time
%cellIDs - array of cellIDs to plot. If empty, all.
%maxRows - maximum number of rows
%plotFrames - should plot nFrames or time
%
%ASM 10/13

%get nCells and nFrames
[nCellsAll,nFrames] = size(dFFTraces);

%create time array
timeSeries = (1:nFrames)/frameRate;

%populate cellIDs
if isempty(cellIDs)
    cellIDs = 1:nCellsAll;
    nCells = nCellsAll;
else
    nCells = length(cellIDs);
end

%initialize
axesHandles = gobjects(1,nCells);
plotHandles = gobjects(1,nCells);
figH = figure('Name','dF/F Traces');

%calculate subplot size
if nCells > maxRows
    nCol = ceil(nCells/maxRows);
    nRows = maxRows;
else
    nCol = 1;
    nRows = nCells;
end

%get minimum value in cells to plot
minVal = min(min(dFFTraces(cellIDs,:)));

%plot dF/F
for i = 1:nCells %for each cell
    
    %get subplot ind
    [rowInd,colInd] = ind2sub([nRows,nCol],i);
    plotInd = sub2ind([nCol,nRows],colInd,rowInd);
    
    %create subplot
    axesHandles(i) = subplot(nRows,nCol,plotInd);
    
    %plot fluorescence trace
    if plotFrames
        plotHandles(i) = plot(dFFTraces(cellIDs(i),:));
    else
        plotHandles(i) = plot(timeSeries,dFFTraces(cellIDs(i),:));
    end
    
    %clear xTickLabel if not at bottom of a column
    if mod(i,nRows) ~= 0 && i ~= nCells
        set(axesHandles(i),'XTickLabel','');
    end
    
    %set yLim
    set(axesHandles(i),'ylim',[minVal 1.1*max(dFFTraces(cellIDs(i),:))]);
    
    
    %set title
    text(1.01,0.5,sprintf('%d',cellIDs(i)),'FontWeight','Bold',...
        'Units','Normalized','FontSize',20,...
        'HorizontalAlignment','Left',...
        'VerticalAlignment','Middle');
       
end

set(axesHandles(:),'FontSize',14);

%set axes labels
if plotFrames
    xString = 'Frame #';
else
    xString = 'Time (s)';
end
[~,xLabHand] = suplabel(xString,'x');
[~,yLabHand] = suplabel('%dF/F','y');
set([xLabHand, yLabHand], 'FontSize',25);